version: '3.8'

services:
  cassandra-api:
    build: ./backend-cassandra
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - odp360-network

  kafka-api:
    build: ./backend-kafka
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - odp360-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - cassandra-api
      - kafka-api
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
      - VITE_KAFKA_API_BASE_URL=http://localhost:8081/api
    networks:
      - odp360-network

networks:
  odp360-network:
    driver: bridge

